export const topbook = [
  {
    id: 1,
    img: "/harrypotter1.jpg",
    title: "Harry Potter và Hòn Đá Phù Thủy",
    oldPrice: "120,000₫",
    newPrice: "90,000₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Cuốn mở đầu hành trình kỳ diệu của Harry Potter – cậu bé phù thủy mồ côi sống với gia đình Dursley khắc nghiệt, bỗng nhận được thư mời nhập học Hogwarts. Ở đây, Harry khám phá sức mạnh phép thuật tiềm ẩn, làm quen Ron và Hermione, phát hiện những bí mật về cha mẹ mình và đối mặt với thế lực hắc ám đe dọa thế giới phù thủy ngay trong năm học đầu tiên.",
  },
  {
    id: 2,
    img: "/harrypotter2.jpg",
    title: "Harry Potter và Phòng Chứa Bí Mật",
    oldPrice: "130,000₫",
    newPrice: "97,500₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Harry trở lại Hogwarts trong năm học thứ hai với hàng loạt sự kiện bí ẩn: Phòng Chứa Bí Mật bị mở, học sinh hóa đá và những lời đồn đáng sợ lan truyền. Cùng Ron và Hermione, cậu phải giải mã di sản của Salazar Slytherin, đối mặt với quái vật nguy hiểm và cứu ngôi trường khỏi hiểm họa đang đe dọa từng ngày.",
  },
  {
    id: 3,
    img: "/lotr1.jpg",
    title: "The Lord of the Rings: Fellowship of the Ring",
    oldPrice: "200,000₫",
    newPrice: "150,000₫",
    discount: "-25%",
    aspect: "2/3",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Phần mở đầu sử thi Chúa Tể Những Chiếc Nhẫn theo chân Frodo Baggins – người thừa kế Chiếc Nhẫn Quyền Lực – cùng Nhóm Bạn Đồng Hành gồm người, elf, dwarf và pháp sư Gandalf khởi hành từ Shire, vượt qua bao hiểm nguy để mang chiếc nhẫn tới Mordor, hủy diệt nó trước khi bóng tối Sauron nuốt chửng Trung Địa.",
  },
  {
    id: 4,
    img: "/lotr2.jpg",
    title: "The Lord of the Rings: The Two Towers",
    oldPrice: "210,000₫",
    newPrice: "157,500₫",
    discount: "-25%",
    aspect: "2/3",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Phần hai tiếp tục cuộc phiêu lưu của Nhóm Bạn Đồng Hành khi họ chia tách để đối phó với những thế lực riêng biệt. Frodo và Sam lặng lẽ tiến vào Mordor dưới sự dẫn dắt mờ ám của Gollum, trong khi Aragorn, Legolas và Gimli dẫn đầu cuộc chiến bảo vệ Rohan chống lại đạo quân khổng lồ của Saruman.",
  },
  {
    id: 5,
    img: "/lotr3.jpg",
    title: "The Lord of the Rings: Return of the King",
    oldPrice: "220,000₫",
    newPrice: "165,000₫",
    discount: "-25%",
    aspect: "2/3",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Phần kết hoành tráng của bộ truyện khi các anh hùng hợp lực trong trận chiến cuối cùng chống Sauron. Aragorn chấp nhận ngôi vị vua, Gandalf dẫn dắt lực lượng con người đánh lạc hướng kẻ thù, còn Frodo và Sam phải vượt qua hiểm nguy để mang Chiếc Nhẫn lên đỉnh Núi Doom và hủy diệt nó.",
  },
  {
    id: 6,
    img: "/hobbit.jpg",
    title: "The Hobbit",
    oldPrice: "180,000₫",
    newPrice: "135,000₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Câu chuyện về Bilbo Baggins – một Hobbit bình dị yêu thích cuộc sống yên ổn – bất ngờ bị cuốn vào chuyến phiêu lưu cùng nhóm chú lùn và pháp sư Gandalf để giành lại kho báu bị rồng Smaug chiếm giữ. Trên đường đi, Bilbo trải qua nhiều thử thách, trưởng thành hơn và phát hiện ra lòng dũng cảm của chính mình.",
  },
  {
    id: 7,
    img: "/percyjackson1.jpg",
    title: "Percy Jackson: The Lightning Thief",
    oldPrice: "150,000₫",
    newPrice: "112,500₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Percy Jackson – cậu bé tưởng như bình thường – phát hiện mình là con trai của Poseidon và bị kéo vào thế giới thần thoại Hy Lạp. Khi bị buộc tội lấy trộm Tia Chớp của Zeus, Percy cùng bạn bè bước vào cuộc phiêu lưu đầy nguy hiểm, chiến đấu với quái vật và tìm hiểu sự thật về nguồn gốc của mình.",
  },
  {
    id: 8,
    img: "/hungergames1.jpg",
    title: "The Hunger Games",
    oldPrice: "160,000₫",
    newPrice: "120,000₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Science fiction",
    cardHeight: "500px",
    width: "100%",
    height: "300px",
    description:
      "Katniss Everdeen tình nguyện thay em gái tham gia Hunger Games – cuộc đấu sinh tử truyền hình trực tiếp giữa các quận. Trong đấu trường khốc liệt, cô vừa phải tìm cách sinh tồn vừa trở thành biểu tượng phản kháng của cả quốc gia, khơi dậy hy vọng cho những con người bị áp bức.",
  },
];
