export const detectiveNovels = [
  {
    id: 21,
    img: "/sherlock1.jpg",
    title: "Sherlock Holmes: Vụ Án Ở Boscombe",
    oldPrice: "120,000₫",
    newPrice: "90,000₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Một trong những vụ án nổi tiếng của thám tử Sherlock Holmes khi ông cùng bác sĩ Watson điều tra cái chết bí ẩn tại Boscombe Valley. Ban đầu mọi bằng chứng đều hướng về một nghi phạm duy nhất, nhưng Holmes bằng sự quan sát tinh tường và phân tích sắc bén đã lật ngược tình thế, vạch trần sự thật ẩn sau những dấu vết tưởng chừng đơn giản.",
  },
  {
    id: 22,
    img: "/sherlock2.jpg",
    title: "Sherlock Holmes: Dấu Bộ Tứ",
    oldPrice: "130,000₫",
    newPrice: "97,500₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Holmes và Watson đối mặt với vụ án phức tạp liên quan tới kho báu Ấn Độ, lời hứa bí mật của những người lính cũ và bốn dấu hiệu kỳ lạ dẫn đến một chuỗi tội ác rùng rợn. Sự nhạy bén của Holmes đưa người đọc qua từng manh mối, mở ra bức tranh âm mưu và lòng tham của con người.",
  },
  {
    id: 23,
    img: "/danbrown1.jpg",
    title: "Mật Mã Da Vinci - Dan Brown",
    oldPrice: "200,000₫",
    newPrice: "150,000₫",
    discount: "-25%",
    aspect: "2/3",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Giáo sư Robert Langdon cùng nữ chuyên gia mật mã Sophie Neveu lần theo chuỗi mật mã bí ẩn ẩn trong các tác phẩm của Leonardo da Vinci để khám phá một âm mưu tôn giáo hàng nghìn năm. Cuộc truy đuổi nghẹt thở qua Paris và London hé lộ những bí mật chấn động về Chén Thánh và lịch sử Ki-tô giáo.",
  },
  {
    id: 24,
    img: "/danbrown2.jpg",
    title: "Thiên Thần và Ác Quỷ - Dan Brown",
    oldPrice: "210,000₫",
    newPrice: "157,500₫",
    discount: "-25%",
    aspect: "2/3",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Cuộc chiến giữa khoa học và tôn giáo bùng nổ khi Robert Langdon được mời đến CERN và sau đó phải ngăn chặn một quả bom hủy diệt giấu trong thành Vatican. Trên đường truy tìm manh mối, ông vạch trần âm mưu của hội Illuminati cổ xưa và chạy đua với thời gian để cứu các Hồng Y khỏi số phận bi thảm.",
  },
  {
    id: 25,
    img: "/agatha1.jpg",
    title: "Án Mạng Trên Sông Nile - Agatha Christie",
    oldPrice: "180,000₫",
    newPrice: "135,000₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Trên du thuyền sang trọng giữa dòng sông Nile, một vụ giết người bí ẩn xảy ra khiến mọi hành khách đều trở thành nghi phạm. Thám tử Hercule Poirot phải sử dụng tài quan sát và suy luận để giải mã từng lời khai, từng mối quan hệ phức tạp để tìm ra hung thủ thật sự trong khung cảnh đầy hào nhoáng.",
  },
  {
    id: 26,
    img: "/agatha2.jpg",
    title: "Mười Người Da Đen Nhỏ - Agatha Christie",
    oldPrice: "150,000₫",
    newPrice: "112,500₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Mười người lạ mặt được mời đến một hòn đảo biệt lập bởi một chủ nhân bí ẩn và lần lượt bị giết theo bài đồng dao kỳ lạ treo trong phòng. Từng chương truyện căng thẳng với bầu không khí ngột ngạt và sự hồi hộp tăng dần, khiến đây trở thành một trong những tác phẩm kinh điển nhất của Agatha Christie.",
  },
  {
    id: 27,
    img: "/trinhtham1.jpg",
    title: "Phía Sau Nghi Can X - Higashino Keigo",
    oldPrice: "170,000₫",
    newPrice: "127,500₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Một thiên tài toán học lập kế hoạch hoàn hảo để che giấu tội ác của người phụ nữ mình yêu. Câu chuyện mở ra cuộc đấu trí căng thẳng giữa hung thủ và vị thám tử thiên tài, hé lộ sự hy sinh, tình yêu, và những tính toán vượt ngoài dự đoán của độc giả.",
  },
  {
    id: 28,
    img: "/trinhtham2.jpg",
    title: "Điều Kỳ Diệu Của Tiệm Tạp Hóa Namiya",
    oldPrice: "140,000₫",
    newPrice: "105,000₫",
    discount: "-25%",
    aspect: "3/4",
    category: "Detective",
    width: "100%",
    height: "300px",
    cardHeight: "500px",
    description:
      "Ba thanh niên trốn vào tiệm tạp hóa cũ và phát hiện ra những lá thư cầu cứu từ quá khứ trôi qua khe cửa. Mỗi bức thư hé lộ một câu chuyện kỳ diệu về sự cảm thông, thay đổi cuộc đời và những bí ẩn kết nối quá khứ – hiện tại trong một vòng tròn ấm áp nhưng đầy bất ngờ.",
  },
];
